### ISSUE TITLE
Add HTTP Gateway

### ISSUE THREAD

**Issue by francoisdtm** [flashenv/flashenv#9]
`http-gateway` authenticates and proxies HTTPS flux to devcontainer. It translate `port.workspace_id.preview.flashenv.dev` to `devcontainer_ip:port`.

It should serve all static files immediately and not proxy them to offload the charge on devcontainers and speed up user interface.

**Comment by e-n-0** [comment]
It's not `port-workspace_id.preview.flashenv.dev` but `port.workspace_id.preview.flashenv.dev`.
Note the dot `.` instead of a hyphen `-`.

**Comment by francoisdtm** [comment]
You're right! My bad
